export const USER_LOADED="USER_LOADED";
export const USER_LOADING="USER_LOADING";
export const AUTH_ERROR="AUTH_ERROR";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";
export const GET_ERRORS="GET_ERRORS";
export const CLEAR_ERRORS="CLEAR_ERRORS";

export const GET_DONORS = 'GET_DONORS';
export const ADD_DONORS= 'ADD_DONORS';
export const DELETE_DONORS = 'DELETE_DONORS';
export const EDIT_DONOR = 'EDIT_DONOR';
export const DONORS_LOADING = 'DONORS_LOADING';
export const SET_CURRENT_DONOR = 'SET_CURRENT_DONOR';
export const CHANGE_CURRENT_DONOR_INFO = 'CHANGE_CURRENT_DONOR_INFO';

export const GET_REQUESTS = 'GET_REQUESTS';
export const ADD_REQUESTS= 'ADD_REQUESTS';
export const ADD_COMMENT= 'ADD_COMMENT';


